[target.aarch64-unknown-linux-gnu]
pre-build = [
  "dpkg --add-architecture $CROSS_DEB_ARCH",
  "apt-get update",
  "apt-get install -y libusb-1.0-0-dev:$CROSS_DEB_ARCH pkg-config"
]

[target.aarch64-unknown-linux-gnu.env]
PKG_CONFIG_LIBDIR="/usr/lib/aarch64-linux-gnu/pkgconfig"

