name: Tests

on:
  push:
    branches:    
      - '**'

env:
  CARGO_TERM_COLOR: always
jobs:
  rust_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt, clippy

      - run: cargo fmt --all -- --check

      - name: Install native packages
        run: sudo apt-get install libhidapi-dev libhidapi-libusb0 libusb-1.0-0 libusb-1.0-0-dev

      - name: Tests
        run: cargo test --all --all-features

      - name: Run clippy manually without annotations
        run: cargo clippy --all-targets --all-features -- -D warnings